# App
spring.application.name=wallet-service
server.port=${PORT:8080}

# PostgreSQL
spring.datasource.url=${JDBC_DATABASE_URL:jdbc:h2:mem:walletdb}
spring.datasource.driver-class-name=${DB_DRIVER:org.h2.Driver}
spring.datasource.username=${PGUSER:sa}
spring.datasource.password=${PGPASSWORD:}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 Console (local only)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console